import { pool } from "../db";
import cron from "node-cron";

let dailyReportTask: cron.ScheduledTask | null = null;

async function getSmtpTransport() {
  const host = process.env.SMTP_HOST;
  const port = process.env.SMTP_PORT;
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;
  if (!host || !port || !user || !pass) return null;
  const nodemailer = (await import("nodemailer")).default;
  return nodemailer.createTransport({ host, port: parseInt(port, 10), secure: parseInt(port, 10) === 465, auth: { user, pass } });
}

async function sendDailyOwnerReport(): Promise<void> {
  try {
    const yesterday = new Date();
    yesterday.setDate(yesterday.getDate() - 1);
    const dateStr = yesterday.toISOString().slice(0, 10);

    const { rows: tenants } = await pool.query(
      "SELECT t.id, t.name, u.email as owner_email FROM tenants t LEFT JOIN users u ON u.tenant_id = t.id AND u.role = 'owner' AND u.email IS NOT NULL AND u.email <> '' WHERE t.active = true"
    );

    const transport = await getSmtpTransport();
    if (!transport) { console.log("[DailyReport] SMTP not configured, skipping"); return; }

    for (const tenant of tenants) {
      if (!tenant.owner_email) continue;
      const [revenue, orders, lowStock] = await Promise.all([
        pool.query(
          "SELECT COALESCE(SUM(total), 0)::numeric as total_revenue, COUNT(*)::int as order_count FROM orders WHERE tenant_id = $1 AND DATE(created_at) = $2 AND status = 'paid'",
          [tenant.id, dateStr]
        ),
        pool.query(
          "SELECT order_type, COUNT(*)::int as cnt FROM orders WHERE tenant_id = $1 AND DATE(created_at) = $2 GROUP BY order_type",
          [tenant.id, dateStr]
        ),
        pool.query(
          "SELECT name, current_stock, min_stock_level FROM inventory_items WHERE tenant_id = $1 AND current_stock <= min_stock_level AND min_stock_level > 0 LIMIT 20",
          [tenant.id]
        ),
      ]);

      const rev = revenue.rows[0];
      const orderBreakdown = orders.rows.map((r: any) => r.order_type + ": " + r.cnt).join(", ") || "None";
      const lowItems = lowStock.rows.map((r: any) => r.name + " (" + r.current_stock + "/" + r.min_stock_level + ")").join(", ") || "All stocked";

      const html = `<h2>Daily Report - ${dateStr}</h2>
        <p><b>Restaurant:</b> ${tenant.name}</p>
        <p><b>Revenue:</b> ${Number(rev.total_revenue).toFixed(2)}</p>
        <p><b>Orders:</b> ${rev.order_count} (${orderBreakdown})</p>
        <p><b>Low Stock Items:</b> ${lowItems}</p>
        <p style="color:#888;font-size:12px">Auto-generated by Table Salt at 8:00 AM</p>`;

      await transport.sendMail({
        from: process.env.SMTP_FROM || process.env.SMTP_USER,
        to: tenant.owner_email,
        subject: "Daily Report - " + tenant.name + " - " + dateStr,
        html,
      });
      console.log("[DailyReport] Sent daily report for tenant", tenant.id);
    }
  } catch (err) {
    console.error("[DailyReport] Error:", err);
  }
}

export function startDailyReportScheduler() {
  if (dailyReportTask) return;
  // Run at 8:00 AM every day
  dailyReportTask = cron.schedule("0 8 * * *", () => { sendDailyOwnerReport(); });
  console.log("[DailyReport] Scheduler started - runs daily at 8:00 AM");
}

export { sendDailyOwnerReport };
